name: osk_flutter
description: Osobisty System Komunikacji

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 3.2.0
  bloc: 3.0.0
  http: 0.12.0+4
  equatable: 1.1.0
  meta: 1.1.8
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true