name: CI

.checkout-template: &checkout-job
  - uses: actions/checkout@v1
  - uses: actions/setup-java@v1
    with:
      java-version: '12.x'
  - uses: subosito/flutter-action@v1
    with:
      channel: 'stable'
  - name: Decrypt secrets
    run: ./.github/scripts/decrypt_secret.sh
    env:
      SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
  - run: flutter pub get


on: push
jobs:
  build-andorid:
    runs-on: linux-latest
    steps:
      - *checkout-job
      - run: flutter build apk
  build-ios:
    runs-on: linux-latest
    steps:
      - *checkout-job
      - run: flutter build ios
